### ISSUE TITLE
Cannot `import RegistryTools` on Julia nightly

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryTools.jl#3]
RegistryTools.jl uses the `Pkg.Compress` submodule. See e.g. https://github.com/JuliaRegistries/RegistryTools.jl/blob/b483113715b1d57e39ddc71ac1d7ae16bf1ca72e/src/register.jl#L195

However, on Pkg master, the `Pkg.Compress` module has been removed. The code is still available in the `bin` directory (https://github.com/JuliaLang/Pkg.jl/tree/master/bin). But the `Pkg.Compress` submodule is not available when you `import Pkg` or `using Pkg`.

Therefore, if you try to `import RegistryTools` on Julia nightly, it fails because the `import Pkg.Compress.load_versions` command fails.

cc: @davidanthoff

**Comment by fredrikekre** [comment]
Isn't part of the reason we created this repository to move that code here? :)

**Comment by DilumAluthge** [comment]
So probably just move the two files in https://github.com/JuliaLang/Pkg.jl/tree/master/bin to this repository, and call it a day?

**Comment by fredrikekre** [comment]
Yea.

**Comment by KristofferC** [comment]
https://github.com/JuliaRegistries/RegistryTools.jl/pull/7
