### ISSUE TITLE
URL case

### ISSUE THREAD

**Issue by oxinabox** [JuliaRegistries/RegistryTools.jl#39]
The check for change of repo URL uses string equality.
https://github.com/JuliaRegistries/RegistryTools.jl/blob/1dff408f07f7bcaca0b2b82eee465ee651c84ade/src/register.jl#L330

This broke a thing for me, since it was mistakenly created as `foobar.jl` rather than `FooBar.jl`,
registered, then fixed.
It doesn't cause any problems since gitlab and github redirect to be case-insensitive AFAIK.

But should we be that demaining?
Apparently by the spec URLs (but not domains) are allowed to be case sensitive.
https://stackoverflow.com/questions/7996919/should-url-be-case-sensitive

**Comment by StefanKarpinski** [comment]
I think we should require a case match.

**Comment by oxinabox** [comment]
Fair enough, we can and do that right now.
