### ISSUE TITLE
Working with registry forks

### ISSUE THREAD

**Issue by staticfloat** [JuliaRegistries/RegistryTools.jl#4]
What is the proper workflow for working with forks of `JuliaRegistries/General`?  In BinaryBuilder, we open pull requests against `General` with the following code:

https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/28a943745baa8d248401d4246efb460e37cb859f/src/AutoBuild.jl#L416-L448

Unfortunately, because we are specifying our fork as the origin to `register()`, we never update the `master` branch of our fork.  This causes our registration PR base commits to fall further and further behind the true upstream `master`.  It almost feels like we need to teach `register()` to take in an `upstream` kwarg, so that it can first reset to `remotes/upstream/master`, then create the new branch.  I believe this workflow will become more and more common as we have more and more bots that do not have commit access to `JuliaRegistries/General`.

**Comment by davidanthoff** [comment]
In PkgDev.jl I don't let `RegistryTools.register` do the push, instead I manually push to the fork, see [here](https://github.com/JuliaLang/PkgDev.jl/blob/master/src/tag.jl#L144). That allows me to pass the origin URL to `register`. But agreed, it would be much more elegant if I could specify another URL to which `register` should actually push.

**Comment by GunnarFarneback** [comment]
Looks like this was implemented in #68.
