### ISSUE TITLE
Allow the default branch of the registry to be specified

### ISSUE THREAD

**Issue by SebRollen** [JuliaRegistries/RegistryTools.jl#50]
Hi,

In `register`, there's an assumption that the default branch of the registry is `master`. I'd like to be able to override this with some other branch (`main`). 
https://github.com/JuliaRegistries/RegistryTools.jl/blob/master/src/register.jl#L652-L653

Happy to issue a pr to just have the branch be passed in as an argument, but figured I'd open the issue first to see if there's any other nuances I should consider in updating the function

**Comment by StefanKarpinski** [comment]
It should ideally just use whatever the default branch of the upstream repo is instead of hard-coding `master`.

**Comment by SebRollen** [comment]
Didn't notice that [this pr](https://github.com/JuliaRegistries/RegistryTools.jl/pull/43) existed before I opened the issue. Maybe we could update that pr to use something like the below to find the default origin branch?
(from [stack-overflow](https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch#:~:text=If%20the%20origin%20repository%20changes,the%20new%20default%20branch%20name.))
`git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'`

**Comment by GunnarFarneback** [comment]
Fixed in #62.
