### ISSUE TITLE
Registering releases older than any other release

### ISSUE THREAD

**Issue by staticfloat** [JuliaRegistries/RegistryTools.jl#6]
**EDIT**: I was confused, the following description is inaccurate:

What is the right way to register a patch release on an old version of a package?  E.g. If I have `1.2.1` and `1.3.0` registered, attempting to register `1.2.2` seems like it will fail due to https://github.com/JuliaRegistries/RegistryTools.jl/blob/8205c026931c730fc31c132a975b417c9a9011f5/src/register.jl#L92-L96.  I ran into this while trying to register a `GSL_jll` for both the `v1.X` series and the `v2.X` series.  Is there a "proper" way to relax this check?

**EDIT**: The true issue is that I registered `v2.X` first, so then `v1.X` is earlier than all other versions.

**Comment by fredrikekre** [comment]
That should be allowed so if it doesn't work then it's a bug.

**Comment by fredrikekre** [comment]
We do have tests for it though, e.g. https://github.com/JuliaRegistries/RegistryTools.jl/blob/8205c026931c730fc31c132a975b417c9a9011f5/test/regedit.jl#L154 and https://github.com/JuliaRegistries/RegistryTools.jl/blob/8205c026931c730fc31c132a975b417c9a9011f5/test/regedit.jl#L178. Could it be your non-standard version strings that causes the trouble maybe?

**Comment by staticfloat** [comment]
Ah, my bug report is confounded.  Let me change the title.  It's because I didn't have a `v1` release before, so the first version it sees is `v2.X`.

**Comment by staticfloat** [comment]
So it is occasionally useful to register a version that is earlier than any other (example: we had previously registered an `Arpack_jll v3.7`, and now we realize that we need to roll it back to `Arpack_jll v3.5`; how can I do that?  (Of course I can do it manually, but I'd like to use the `RegistryTools` when I can)

**Comment by vchuravy** [comment]
I just run into this issue with `LLVM_jll`

https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/commit/1818729349ad3b123c888da1b05ef5a33924aaaf#commitcomment-36937315

**Comment by KristofferC** [comment]
Why is this an error at all? Who does it help?

**Comment by staticfloat** [comment]
I'm not sure the right way to fix this, since I don't fully follow the logic of [finding the previous/next versions](https://github.com/JuliaRegistries/RegistryTools.jl/blob/master/src/register.jl#L92-L118), but it would be really great to remove this error.  I don't think it really helps anyone, and it routinely causes problems in the BB world where we build (for instance) OpenBLAS v0.3.7, then decide we want v0.3.5 as well, and our registrations never go through.

**Comment by StefanKarpinski** [comment]
It seems better to just make an exception for BB registrations and not check their version numbers. This _would_ be a weird thing to do for a normal package.

**Comment by giordano** [comment]
> This would be a weird thing to do for a normal package.

One can maintain old versions of packages for bug fixes

**Comment by StefanKarpinski** [comment]
That wouldn't be triggered by this check.

**Comment by GunnarFarneback** [comment]
I don't find it unreasonable to register a package and then later realize that you would also want earlier versions in in your registry. This is maybe undesirable in the General registry but I don't see why it should be so weird that you cannot use RegistryTools to do such updates in your own registry.

**Comment by StefanKarpinski** [comment]
You can do that, but it should require human intervention and not go through automatically. Once again: none of these checks are mandatory.

**Comment by GunnarFarneback** [comment]
I just can't see any way to opt out of that check if I want to use RegistryTools.

**Comment by staticfloat** [comment]
What Gunnar is referring to is that there are checks built in to `RegistryTools` in opening a registration request at all; it's separate from the automerger; this is the tool that actually opens a pull request.

**Comment by GunnarFarneback** [comment]
More specifically it goes like this when you call `register` with an older version than previously registered:
* `register` calls `update_versions_file`.
* `update_versions_file` calls `check_version!`.
* `check_version!` doesn't like the version and signals it as an error (not a warning, in contrast to some other checks).
* `update_versions_file` aborts without touching the versions file.
* `register` aborts.

**Comment by KristofferC** [comment]
Yes, the point here is that RegistryTools itself has built-in policy decisions that it just errors on which shouldn't be the case.

**Comment by GunnarFarneback** [comment]
Agreed. The caller should decide the policy unless the integrity of the registry would be compromised.

**Comment by GunnarFarneback** [comment]
With #16 this error can be opted out of by the caller of `register`. The only additional change that can be made in this package is the RFC PR #19 which changes it from opt-out to opt-in.

**Comment by giordano** [comment]
> With #16 this error can be opted out of by the caller of register

Can we have a new release so that we can actually do this? :slightly_smiling_face:

**Comment by GunnarFarneback** [comment]
RegistryTools 1.3 has been registered.

**Comment by giordano** [comment]
> With #16 this error can be opted out of by the caller of register

Ehm... how?  I failed to find this information anywhere: there is no ChangeLog and the description of #16 doesn't explain what users have to do, unless I am supposed to read the 23-file diff in #16 :grimacing:

**Comment by GunnarFarneback** [comment]
The shortage of documentation is not exactly a regression, but yes, I missed to even update the docstring for `register`. Anyway, the general idea would be something like
```
errors = setdiff(RegistryTools.registrator_errors, [:version_less_than_all_existing])
register(..., checks_triggering_error = errors)
```
> unless I am supposed to read the 23-file diff in #16

It's ok if you skip the 19 added test data files. I would worry more about reading the 556 line changes in `register.jl`. :-)

**Comment by giordano** [comment]
Ok, thanks!  I opened https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/712

**Comment by GunnarFarneback** [comment]
Ah, my changes only takes it halfways (unless you bypass the `register` function like I do in LocalRegistry). I believe #29 should fix the problem.

**Comment by giordano** [comment]
As far as I can tell, after last fixes by @GunnarFarneback, [this PR](https://github.com/JuliaPackaging/Yggdrasil/pull/790) in Yggdrasil successfully triggered the [registration](https://github.com/JuliaRegistries/General/pull/12506) of a version older than any already registered version.
