### ISSUE TITLE
Update to registry branch fails if the branch was created by old version of RegistryTools

### ISSUE THREAD

**Issue by vdayanand** [JuliaRegistries/RegistryTools.jl#70]
Error:
```
 ! [remote rejected] HEAD -> registrator/testpackage/7876af07/v0.13.19/59175fcecb (cannot lock ref 'refs/heads/registrator/testpackage/7876af07/v0.1.1/59175fcecb': 'refs/heads/registrator/testpackage/7876af07/v0.0.1' exists; cannot create 'refs/heads/registrator/privateexample3/7876af07/v0.13.19/59175fcecb')
```

With RegistryTool version < 1.6.0 , branch created on registry of form `/registrator/<packagename>/<uuid slug>/<version>`
With https://github.com/JuliaRegistries/RegistryTools.jl/pull/63, we have `/registrator/<packagename>/<uuid slug>/<version>/url_hash`.  
As per https://stackoverflow.com/questions/22630404/git-push-refs-heads-my-subbranch-exists-cannot-create/22630664#22630664, we cannot force a branch `A/x` if `A` exists. 

So can we use `-` instead of `/` ie `registrator/<packagename>/<uuid slug>/<version>-<url_hash>` instead of `registrator/<packagename>/<uuid slug>/<version>/<url_hash>` ?

 @DilumAluthge @nkottary

**Comment by nkottary** [comment]
I think the GitHub actions on General registry depends on the `/<url_hash>` ? @DilumAluthge

**Comment by fredrikekre** [comment]
Where are there such old branches? Wouldn't it be easier to just delete those and start over?

**Comment by nkottary** [comment]
> Where are there such old branches? Wouldn't it be easier to just delete those and start over?

I updated my comment above. Basically:
> If we upgrade Registrator it will create branches in the new format. So if someone created a PR with the current registrator and re-registers after the upgrade then the above error will occur.

**Comment by DilumAluthge** [comment]
> Why was the url hash added to the branch name? Does it help with CI or something?

It's necessary to mitigate a potential security issue.
