### ISSUE TITLE
Bad test now errors

### ISSUE THREAD

**Issue by KristofferC** [JuliaRegistries/RegistryTools.jl#99]
Don't know what this is trying to test exactly:

https://github.com/JuliaRegistries/RegistryTools.jl/blob/77e2a02e62185ce865653bdae95203a3a40510f0/test/regedit.jl#L333-L336

Right now it gets

```
compat_file: Test Failed at /home/pkgeval/.julia/packages/RegistryTools/2CM18/test/regedit.jl:333
  Expression: read(compat_file, String) == "[1]\njulia = \"1.3.0-1\"\n"
   Evaluated: "[1]\njulia = \"1.3.0 - 1\"\n" == "[1]\njulia = \"1.3.0-1\"\n"
``

**Comment by GunnarFarneback** [comment]
I do https://github.com/GunnarFarneback/LocalRegistry.jl/blob/master/test/utils.jl#L114-L122 in the LocalRegistry tests but I'm curious why this formatting changed, so I can update the comment in that excerpt.

**Comment by DilumAluthge** [comment]
Introduced in https://github.com/JuliaLang/Pkg.jl/pull/3580 I believe.
